---
config:
  default: true
  line-length:
    line_length: 120
gitignore: true
ignores:
  - CHANGELOG.md
overrides:
  - filter:
      - README.md
    config:
      no-bare-urls: false
    combine: "merge"
