---
name: Release

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published

permissions:
  packages: write
  contents: read
  attestations: write
  id-token: write

jobs:
  release:
    name: Build and push XC atlantis image to registries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            memes/xc-atlantis
            ghcr.io/${{ github.repository }}/xc-atlantis
          tags: |
            type=semver,pattern={{version}},value=${{ steps.release_please.outputs.tag_name }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.release_please.outputs.tag_name }}
          labels: |
            maintainer=memes@matthewemes.com
            org.opencontainers.image.title=xc-atlantis
            org.opencontainers.image.description=Atlantis container with added tools for F5XC.
            org.opencontainers.image.url=https://github.com/${{ github.repository }}/tree/${{ github.sha }}/containers/xc-atlantis/
            org.opencontainers.image.documentation=https://github.com/${{ github.repository }}/tree/${{ github.sha }}/containers/xc-atlantis/README.md
      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./containers/xc-atlantis
          file: ./containers/xc-atlantis/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation for Docker Hub
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/memes/xc-atlantis
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
      - name: Generate artifact attestation for GHCR
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository }}/xc-atlantis
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
